# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 72af9d2537729737bba82a336aff7d9bf71f075e89c39e95a707c12c4b88a7054794d3dfc9f084b1d965704d25d81a7469a4df21ed40f7cbc71a6e473f14d494

test:
  secret_key_base: 49c8164a8cc2dbc6094205ca5b1fb0d4af44d63acf0d2f55a194c0c3cec649bbe4020443726c46fa92359ee9abe94d1baf52da73c88f2e1f4d2c319ed79c5f39

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
